version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: decode_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: decode_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
