/*
 * This source file was generated by the Gradle 'init' task
 */
package com.codedifferently.projectoop.decode;

import org.junit.jupiter.api.Test;

import com.codedifferently.projectoop.decode.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
