/*
 * This file was generated by the Gradle 'init' task.
 * It defines a basic Java CLI application using Kotlin DSL.
 */

plugins {
    application
    id("com.adarshr.test-logger") version "4.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // If you're not using a version catalog, replace libs.guava with this:
    implementation("com.google.guava:guava:32.1.3-jre")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("decode.App")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
